# Generated by Django 4.0.5 on 2022-06-17 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_followers_follower_alter_followers_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='following',
        ),
        migrations.RemoveField(
            model_name='followers',
            name='follower',
        ),
        migrations.AddField(
            model_name='followers',
            name='follower',
            field=models.ManyToManyField(related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
